# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "debian/jessie64"

  config.vm.network :forwarded_port, guest: 22, host: 7023, id: "ssh"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get -y install git g++ cmake libreadline-dev ccache default-jre
    # Add missing symlinks to ccache dir
    (cd /usr/lib/ccache; sudo ln -s ../../bin/ccache c++)
    (cd /usr/lib/ccache; sudo ln -s ../../bin/ccache cc)
    ccache -M 5G
  SHELL
end
